OPT_DEFS += -DSPLIT_TRANSACTION_IDS_USER='USER_SYNC_LIGHTS_A, USER_SYNC_LIGHTS_B, USER_DYNAMIC_LIGHTS_STARTUP, USER_SYNC_RGB_DIRECT'
SRC += dynamic_lights.c
SRC += audio_visualizer.c
RAW_ENABLE = yes
VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = yes
VIAL_INSECURE = yes

ENCODER_MAP_ENABLE = yes

RGB_MATRIX_CUSTOM_USER = yes

# Debug
CONSOLE_ENABLE = no