OPT_DEFS += -DSPLIT_TRANSACTION_IDS_USER='USER_SYNC_LIGHTS_A, USER_SYNC_LIGHTS_B'
SRC += dynamic_lights.c
VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = yes
VIAL_INSECURE = yes

ENCODER_MAP_ENABLE = yes